### PR TITLE
`AUTOBUILD` Script

### PR DESCRIPTION
**Pull request by sadernalwis**
+ `yarn autobuild` command
+ `wasm/` directory to `.gitignore`

### CODE REVIEW

**Comment by b3hr4d** [comment]
I have change `wasm` directory to `canisters`, do we still need it inside `.gitignore` ?

**Comment by sadernalwis** [comment]
I guess not, let me confirm.

**Comment by b3hr4d** [comment]
This script is super useful, Also can you add the --help command for this?

**Comment by sadernalwis** [comment]
yes. will do.. closing this PR till then.

**Comment by sadernalwis** [comment]
You were right. `wasm` in the `.gitignore` no longer needed.

**Comment by b3hr4d** [comment]
Use Ai for this. the result should be great on this type of script.

**Comment by b3hr4d** [comment]
To add a `--help` command to your script, you can include a section at the beginning of the script that checks if the first argument (`$1`) is `--help`. If it is, the script should print a help message describing what the script does and how to use it, then exit without executing any further commands.

Here's an example of how you can modify your script to include a `--help` command:

```bash
#!/bin/bash

# ... [Your existing variable definitions] ...

log() {
  local color="$1" # First argument
  local message="$2" # Second argument
  echo -e "${color}${message}${NO_COLOR}"
}

# Help message function
print_help() {
  echo "Usage: $0 [command] [options]"
  echo
  echo "Commands:"
  echo "  clean        Remove all files and clone repositories"
  echo "  predeploy    Run pre-deployment scripts"
  echo "  start        Start DFX, optionally with bitcoin support"
  echo "  deploy       Deploy the application"
  echo "  --help       Display this help message"
  echo
  echo "Options for 'start':"
  echo "  bitcoin      Enable bitcoin support in DFX"
  echo
  echo "Example:"
  echo "  $0 deploy         # Deploy the application"
  echo "  $0 start bitcoin  # Start DFX with bitcoin support"
}

# Check if the first argument is --help
if [ "$1" = "--help" ]; then
  print_help
  exit 0
fi

# ... [Rest of your script] ...

```

In this modification:

1. I added a `print_help` function that prints the usage instructions and descriptions of the available commands.
2. The script checks if the first argument is `--help`. If it is, it calls the `print_help` function and then exits.
3. Users can now run your script with `--help` to get information about how to use it.

This approach provides a clear and user-friendly way to inform users about the script's functionality and usage.

**Pull request closed without merging**
